' Alt + D
@startuml hoge
agent Jetson_Orin
agent ZEDX
agent VN200
agent ポテンショメータ
agent スイッチングハブ
agent 無線LANブリッジ
agent ブレーキ
agent ブレーキ用リミットセンサー
agent モータドライバ_駆動用モーター
agent PC_DELL

agent 制御用基板
agent MPP制御基板
agent 電源SW_LEDインジケータ基板
agent MPP

(GNSSアンテナ)
(UECER_NV)
(ディスプレイ)

Jetson_Orin --up-> ZEDX:専用のコネクタ
Jetson_Orin -up-> (UECER_NV)
(UECER_NV) -left-> (GNSSアンテナ):白い配線
Jetson_Orin -> (ディスプレイ):HDMI

Jetson_Orin --> スイッチングハブ

スイッチングハブ -up-> 無線LANブリッジ
スイッチングハブ -down-> PC_DELL

PC_DELL --> VN200

package "制御用基板" {
    [AP_RX62N_OA]
    [PSoC_制御]
}

AP_RX62N_OA .right.> PSoC_制御:CAN
AP_RX62N_OA .down.> モータドライバ_駆動用モーター:CAN
AP_RX62N_OA -left-> スイッチングハブ

PSoC_制御 -down-> ポテンショメータ:AN
PSoC_制御 -up-> ブレーキ:専用I/F
PSoC_制御 -right-> ブレーキ用リミットセンサー:ON/OFF

package "MPP制御基板" {
    [Battery12V_昇圧回路]
    [PSoC_MPP]
}

package "電源SW_LEDインジケータ基板"{
    [電源SW]
    [LED]
}

PSoC_MPP -> LED
LED -> PSoC_MPP

電源SW -> Battery12V_昇圧回路
Battery12V_昇圧回路 -> 電源SW

PSoC_MPP ..> MPP:CAN

MPP --> (300W)
MPP ..> (USB_CAN変換):CAN
MPP --> (200W_48Vto24V)
MPP --> (200W_48Vto48V)
MPP --> (プリチャージ用リレー)

(プリチャージ用リレー) --> (シャント抵抗)
(プリチャージ用リレー) --> (サージ吸収用ダイオード)
(シャント抵抗) -->  (駆動用電源リレー)
(サージ吸収用ダイオード) --> (駆動用電源リレー)

(駆動用電源リレー) --> (緊急停止ボタン)
(緊急停止ボタン) --> AP_RX62N_OA

(200W_48Vto24V) --> (24Vto12V)
(200W_48Vto24V) --> (手動スイッチ1)
(手動スイッチ1) --> (24Vto5V)

(300W) --> (90W)
(300W) --> (100W)

(90W) --> PC_DELL
(100W) --> Jetson_Orin

(USB_CAN変換) ..> PC_DELL:CAN



@enduml