' Alt + D
@startuml hoge
agent Jetson_Orin
agent ZEDX
agent VN200
agent ポテンショメータ
agent スイッチングハブ
agent 無線LANブリッジ
agent ブレーキ
agent ブレーキ用リミットセンサー
agent モータドライバ_駆動用モーター
agent PC_DELL


agent 制御用基板


(GNSSアンテナ)
(UECER_NV)
(ディスプレイ)

Jetson_Orin --up-> ZEDX:専用のコネクタ
Jetson_Orin -up-> (UECER_NV)
(UECER_NV) -left-> (GNSSアンテナ):白い配線
Jetson_Orin -> (ディスプレイ):HDMI

Jetson_Orin -left-> (PC-DELL)
(PC-DELL) -> VN200

Jetson_Orin -> (jetsonスイッチ)
Jetson_Orin --> スイッチングハブ

スイッチングハブ -up-> 無線LANブリッジ
スイッチングハブ --> PC_DELL

package "制御用基板" {
    [AP-RX62N-OA]
    [CY8CKIT-C43]
}

制御用基板 -right-> ポテンショメータ
制御用基板 -up-> ブレーキ
制御用基板 -right-> ブレーキ用リミットセンサー
制御用基板 -up--> モータドライバ_駆動用モーター
制御用基板 -left-> スイッチングハブ

@enduml